### ISSUE TITLE
[Intro to iOS] Week 3 Assignment: Review my app

### ISSUE THREAD

**Issue by marcel** [marcel/Twitter#1]
/cc @codepath

**Comment by codepathreview** [comment]
:+1: nice work. The point of this homework was to explore a simple example of a full MVC application with a RESTful API. For each point in the homework feedback checklist, I'll either confirm that you're on the right track with the implementation, or I'll provide some feedback:
- love the zero-characters animation!
- I had a crash, probably data missing in the Twitter json: fatal error: unexpectedly found nil while unwrapping an Optional value on #1    0x0000000100134d80 in TweetCell.tweet.didset at /Users/dirkdk/testprojects/codepath/marcel/Twitter/Twitter/TweetCell.swift:43
- Nice work using private scope for your properties and your functions for better encapsulation.
- Nice work specifying the Auto Layout constraints.
- Nice work handling the retweet label/image by dynamically modifying the constraint. This is a situation where its not possible to specify the behavior that you want solely using Interface Builder.
- Nice work setting up the controls within the Tweet cells. It can sometimes be hard to have a clean design for embedded controls because it usually involves cumbersome plumbing. This is an instance where I think having the model handle the network action helps greatly simplify the implementation.
- You should try implementing the post tweet insertion into the feed. In real MVC apps, the more polished experiences have to do a certain amount of local object management to make a fully seamless experience.

In general, you should challenge yourself to create visually polished applications. That's where you'll find all the rough edges of the iOS framework and earn the next level of mastery.

-- dirk
